Initial version of Terraform schema & unmarshallers generator
gravitational/protoc-gen-terraform pull request #1
Opened 2021-02-24 18:43 UTC by gzigzigzeo

2021-02-26 21:01 UTC, a-palchikov commented on plugin/main.go
> +			p.Generator.Fail(trace.Wrap(err).Error())
No need to `trace.Wrap` for just the error message.

2021-03-01 08:56 UTC, gzigzigzeo commented on test/custom_types.go
> +type SomethingCustom int
No, removed.

2021-03-01 09:39 UTC, gzigzigzeo commented on README.md
> +This will generate `types_terraform.go` in _out directory. This file will contain `UnmarshalUserV2` and `UnmarshalRolesV3` along with `SchemaUserV2` and `SchemaRolesV3` methods. Target package name s
Thank you for the review!

There are two problems: target package name and imports.

Package name is hardcoded by gogo-protobuf. In order to change it, I might need to generate the whole header block manually, which I would like to avoid. Better approach would be to patch gogo-protobuf itself and add this feature.

Imports are little bit tricky. gogo-protobuf records all the packages which are referenced by any fields in a source proto file and adds them to a target file, but since we export a limited list of target messages, some imports referenced by non-rendered messages are written as well. gogo-protobuf runs gofmt over a target file, it does not help. 

I think, I could try to manually replace package name and use goimports on a target file (which is essentially gofmt with the ability to manage imports). I am just not there yet. Since this is initial version, I propose to leave this as is. It is in my plans (and TODO list) to fix it in next versions.

2021-03-01 16:59 UTC, klizhentas commented on config/main.go
> +func ParseTypes(arg string) {
in Teleport functions that panic start with `MustParseTypes`

2021-03-01 18:49 UTC, gzigzigzeo commented
Just in case, here's the list of dependency licenses:

```csv
github.com/Masterminds/goutils,https://github.com/Masterminds/goutils/blob/master/LICENSE.txt,Apache-2.0
github.com/huandu/xstrings,https://github.com/huandu/xstrings/blob/master/LICENSE,MIT
github.com/gravitational/protoc-gen-terraform,Unknown,Apache-2.0
github.com/google/uuid,https://github.com/google/uuid/blob/master/LICENSE,BSD-3-Clause
github.com/imdario/mergo,https://github.com/imdario/mergo/blob/master/LICENSE,BSD-3-Clause
github.com/mitchellh/copystructure,https://github.com/mitchellh/copystructure/blob/master/LICENSE,MIT
github.com/stoewer/go-strcase,https://github.com/stoewer/go-strcase/blob/master/LICENSE,MIT
github.com/gogo/protobuf,https://github.com/gogo/protobuf/blob/master/LICENSE,BSD-3-Clause
github.com/stretchr/stew/slice,https://github.com/stretchr/stew/blob/master/slice/README.md,MIT
github.com/Masterminds/semver,https://github.com/Masterminds/semver/blob/master/LICENSE.txt,MIT
golang.org/x/sys,Unknown,BSD-3-Clause
github.com/Masterminds/sprig,https://github.com/Masterminds/sprig/blob/master/LICENSE.txt,MIT
github.com/mitchellh/reflectwalk,https://github.com/mitchellh/reflectwalk/blob/master/LICENSE,MIT
golang.org/x/crypto,Unknown,BSD-3-Clause
github.com/sirupsen/logrus,https://github.com/sirupsen/logrus/blob/master/LICENSE,MIT
```

2021-03-02 12:44 UTC, gzigzigzeo commented on README.md
> +func SchemawrappersLabelValues(string path, data *schema.ResourceData, target *types.Traits) error
Yes, wrappers is the package name. How do you think, should I capitalise it as well?

2021-03-02 12:45 UTC, gzigzigzeo commented on config/main.go
> +// ParseDuration parses duration custom class
Good point, will rename.

2021-03-02 13:02 UTC, gzigzigzeo commented on Makefile
>  	@echo "Teleport source code is required to build this example!"
Thank you, fixed

2021-03-02 13:14 UTC, gzigzigzeo commented on README.md
> +func SchemawrappersLabelValues(string path, data *schema.ResourceData, target *types.Traits) error
Fixed naming in README in separate commit.

2021-03-02 13:59 UTC, a-palchikov commented on README.md
> +func SchemawrappersLabelValues(string path, data *schema.ResourceData, target *types.Traits) error
I have not gotten enough details to know how this works internally, but usually package name is not encoded in the method names - instead the serialization could be placed into the corresponding package?

So, for `wrappers.LabelValues` it could be `wrappers.SchemaLabelValues` and `wrappers.UnmarshalLabelValues` placed under wrappers/serialization.go.

Not sure why the marshaler is called Schema though.

2021-03-02 14:41 UTC, gzigzigzeo commented on Makefile
> +terraform: build
Done!

2021-03-02 14:55 UTC, gzigzigzeo commented on README.md
> +func SchemawrappersLabelValues(string path, data *schema.ResourceData, target *types.Traits) error
Marshaller is called Unmarshal, it was my mistake in the README, fixed it already.

The purpose of this methods is to provide overrides for fields marked with gogo.customtype flag. Such fields structure  could not be reflected at the generation stage. This methods must be provided by the target code (check customtypes.go at https://github.com/gravitational/teleport-plugins/pull/197/files#, please), Schema* and Unmarshal* for every type referenced. 

I do not see any benefits of sub packaging them. There might be several sub packages (wrappers, roles, etc.) containing just a single pair of methods each.

2021-03-04 10:09 UTC, gzigzigzeo commented on README.md
> +This will generate `types_terraform.go` in _out directory. This file will contain `UnmarshalUserV2` and `UnmarshalRolesV3` along with `SchemaUserV2` and `SchemaRolesV3` methods. Target package name s
Fixed this with latest commit, target file won't contain any unused dips anymore

2021-03-04 12:19 UTC, a-palchikov commented on plugin/field.go
> +	// IsMessage field is message? (might be map or list in the same time)
```suggestion
	// IsMessage field is message? (might be map or list at the same time)
```

2021-03-04 12:19 UTC, a-palchikov commented on plugin/field.go
> +	// Prepend package name to overriden field type
```suggestion
	// Prepend package name to overridden field type
```

2021-03-04 12:19 UTC, a-palchikov commented on plugin/field.go
> +		// Is cast type is within current package, append default package name to it
```suggestion
		// If cast type is within current package, append default package name to it
```

2021-03-04 12:19 UTC, a-palchikov commented on render/main.go
> +// Template renders template from string to bytes.buffer
```suggestion
// Template renders template from string to the specified writer
```

2021-03-04 13:25 UTC, gzigzigzeo commented on main.go
> +	n1 := strings.Index(s, "package")
Yes, added check & warning Just warning because a) situation is hardly possible b) I think, we should not fail totally if some dependency file failed to generate.

2021-03-11 19:33 UTC, klizhentas requested changes

2021-03-11 19:33 UTC, klizhentas commented on main.go
> +	r := s[0:n1+8] + config.TargetPkgName + s[n1+n2:]
this could be quite fragile, can you please start with `filepath.Split` here to get the package name or a regular expression

https://github.com/gravitational/trace/blob/master/trace.go#L285

2021-03-11 19:33 UTC, klizhentas commented on plugin/field.go
> +	"github.com/gravitational/protoc-gen-terraform/config"
please split imports into 3 groups as described here:

https://github.com/golang/go/wiki/CodeReviewComments#imports

2021-03-11 19:33 UTC, klizhentas commented on plugin/field.go
> +	// GoTypeIsSlice Go type is a slice?
`GoTypeIsSlice` specifies whether Go type is a slice

2021-03-11 19:33 UTC, klizhentas commented on plugin/field.go
> +// fieldBuilder is axilarry struct responsible for building Field
please apply @a-palchikov comment

2021-03-11 19:33 UTC, klizhentas commented on plugin/field.go
> +		if slice.Contains(config.ExcludeFields, typeName) {
if your `ExcludeFields` are `map[string]struct{}` this will be  more efficient, as you'd initially have to skip many types

2021-03-11 19:33 UTC, klizhentas commented on plugin/field.go
> +func BuildField(g *generator.Generator, d *generator.Descriptor, f *descriptor.FieldDescriptorProto) *Field {
In Teleport's control flow, we always return error and then let the caller to decide what to do with it. In this case the function will return `trace.BadParameter` error alongside field, and the caller of Build can decide whether to skip it. Any reason why we should be skipping fields in general?

2021-03-11 19:33 UTC, klizhentas commented on plugin/field.go
> +		return err
please use trace.Wrap as @a-palchikov suggested

2021-03-11 19:33 UTC, klizhentas commented on plugin/field.go
> +		b.generator.Fail("unknown type for", b.descriptor.GetName(), b.fieldDescriptor.GetName())
return `trace.BadParameter` here. Please follow the error handling we use elsewhere - return the error and let the caller to decide whether to skip it.

2021-03-11 19:33 UTC, klizhentas commented on plugin/field.go
> +	f := b.field // shortrut
shortcut, what is it shortcut for?

2021-03-11 19:33 UTC, klizhentas commented on plugin/field.go
> +		return fmt.Errorf("Nested message is invalid for field %v", b.field.Name)
please use `trace.BadParameter` here instead of `fmt.Errorf`. In general, please use `trace` package

2021-03-11 19:33 UTC, klizhentas commented on plugin/field.go
> +// setMessage sets reference to nested message
can you give examples, it's hard to understand what is a reference and nested message, can you also provide examples for other similar cases.

2021-03-11 19:33 UTC, klizhentas commented on plugin/field.go
> +// Sets IsList and IsMap flags
setAggregate detects and sets IsList and IsMap flags.

2021-03-11 19:33 UTC, klizhentas commented on plugin/main.go
> +const (
set comments to conform to https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences

2021-03-11 19:33 UTC, klizhentas commented on plugin/message.go
> +// Message holds reflection information about message
what is a Message in this context?

2021-03-11 19:33 UTC, klizhentas commented on test/main_test.go
> +func TestUnmarshal(t *testing.T) {
Please switch to https://github.com/gravitational/teleport/blob/master/lib/utils/slice_test.go#L6

testify/require package instead of panics

2021-03-11 19:33 UTC, klizhentas commented on test/main_test.go
> +	subject, _ := buildSubject(t)
@gzigzigzeo here and below, let's never skip or ignore any errors.

2021-03-11 19:33 UTC, klizhentas commented on test/test.proto
> +    // --- Nested maps ----------------------------------------------------------------------
let's remove `-----` style comments here and below

2021-03-11 19:33 UTC, klizhentas commented on test/test.proto
> +message Test {
// Test contains elementary fields

2021-03-12 12:01 UTC, gzigzigzeo commented on test/main_test.go
> +	subject, _ := buildSubject(t)
Yep, I think that here and in previous step, I tried to unnecessarily DRY tests. So, instead of panicking, I would better check this error every time with require package and eliminate TestUnmarshal method.

2021-03-12 12:06 UTC, gzigzigzeo commented on test/test.proto
> +message Test {
Fixed, made comment more explicit at all

2021-03-12 12:06 UTC, gzigzigzeo commented on test/test.proto
> +    // --- Nested maps ----------------------------------------------------------------------
Done

2021-03-12 12:07 UTC, gzigzigzeo commented on test/main_test.go
> +func TestUnmarshal(t *testing.T) {
Done

2021-03-12 12:18 UTC, gzigzigzeo commented on build.assets/Dockerfile
> +RUN set -ex && \
Custom user is required to avoid host system root access from inside the container. https://github.com/gravitational/protoc-gen-terraform/pull/1#discussion_r585480447 - I've considered this as the default security practice since this file was given to me as is. Thought that your CI setup might use it for some reason. I could remove this block if you think it's safe.

2021-03-12 12:26 UTC, gzigzigzeo commented on build.assets/Dockerfile
> +RUN set -ex && \
If you mean "genet ||" statement specifically - "create if not exists", if I am not mistaken.

2021-03-12 12:31 UTC, gzigzigzeo commented on config/main.go
> +// Package config contains global configuration variables and methods to parse them
Done. How should I proceed with the generated code? I believe, that should be the responsibility of a target user.

2021-03-12 12:35 UTC, gzigzigzeo commented on main.go
> +	r := s[0:n1+8] + config.TargetPkgName + s[n1+n2:]
filepath.Split is not applicable here because user should provide package name as a pure string, without any path spec. Package name of a generated file is hardcoded on gogoprotobuf side and always equals to a package name specified in source file. In our case, it should be changeable because instead of struct definitions, we generate terraform schema and unmarshallers which may reside anywhere in the target code.

2021-03-12 12:41 UTC, gzigzigzeo commented on main.go
> +	r := s[0:n1+8] + config.TargetPkgName + s[n1+n2:]
In another hand, it won't hurt to add it in case user will specify full path spec. Done, in config/main.go

2021-03-12 13:05 UTC, gzigzigzeo commented on main.go
> +		logrus.Println("Warning: package directive not found in target file, can't replace package name, skipping")
Yep. I have completely replaced this fragment with regexp. Doing it current way is OK, but less readable than regexp.

2021-03-12 13:08 UTC, gzigzigzeo commented on plugin/field.go
> +	"github.com/gravitational/protoc-gen-terraform/config"
Sorry, I do not get it. You mean, make config inclusion separate?

2021-03-12 13:15 UTC, gzigzigzeo commented on plugin/field.go
> +// getFieldTypeName returns field name with package
Done

2021-03-12 13:15 UTC, gzigzigzeo commented on plugin/field.go
> +// newFieldBuilder constructs an empty fieldBuilder struct
Done

2021-03-12 13:15 UTC, gzigzigzeo commented on plugin/field.go
> +		return err
Done

2021-03-12 13:16 UTC, gzigzigzeo commented on plugin/field.go
> +// isTypeEq returns true if type
Fixed

2021-03-12 13:16 UTC, gzigzigzeo commented on plugin/field.go
> +// isTime returns true if field stores time (is standard, google or golang time)
Fixed

2021-03-12 13:17 UTC, gzigzigzeo commented on plugin/field.go
> +// resolveType analyses field type and sets required fields in Field structure
Fixed

2021-03-12 13:17 UTC, gzigzigzeo commented on plugin/field.go
> +// isDuration return true if field stores duration (is standard duration, or casted to duration)
Fixed

2021-03-12 13:34 UTC, gzigzigzeo commented on config/main.go
> +		logrus.Fatal("Please, specify explicit top level type list, eg. --terraform-out=types=UserV2+UserSpecV2:./_out")
Done

2021-03-12 13:39 UTC, gzigzigzeo commented on config/main.go
> +	DefaultPkgName = arg
This is complete. Initially, I thought that it would be better to keep Parse methods for cases where some kind of parsing is involved (like .Split), but decided to rename all to Set since Split it's not the extensive parsing.

2021-03-12 13:41 UTC, gzigzigzeo commented on plugin/field.go
> +// fieldBuilder is axilarry struct responsible for building Field
Applied

2021-03-12 13:58 UTC, gzigzigzeo commented on plugin/field.go
> +		if slice.Contains(config.ExcludeFields, typeName) {
TIL, nice trick, thank you. Changed for both Types and ExcludeFields.

2021-03-12 14:01 UTC, gzigzigzeo commented on plugin/field.go
> +// Append type suffix to cast type, custom type or message
Yep )

2021-03-12 14:02 UTC, gzigzigzeo commented on plugin/field.go
> +// setGoType Sets go type with gogoprotobuf standard method, sets type information flags
Fixed

2021-03-12 14:18 UTC, gzigzigzeo commented on plugin/field.go
> +	// This is an exception: we get all []byte arrays from strings, it is an elementary type on protobuf side
Fixed

2021-03-12 14:18 UTC, gzigzigzeo commented on plugin/field.go
> +		return fmt.Errorf("Nested message is invalid for field %v", b.field.Name)
Done

2021-03-12 14:19 UTC, gzigzigzeo commented on plugin/field.go
> +		return fmt.Errorf("Nested message is invalid for field %v", b.field.Name)
Fixed

2021-03-12 14:19 UTC, gzigzigzeo commented on plugin/field.go
> +// Sets IsList and IsMap flags
👍

2021-03-12 14:19 UTC, gzigzigzeo commented on plugin/field.go
> +// Sets gogo.customtype flag
👍

2021-03-12 14:20 UTC, gzigzigzeo commented on plugin/field.go
> +// reflectMap sets map value properties
👍

2021-03-12 14:21 UTC, gzigzigzeo commented on plugin/main.go
> +const (
Looks like comments are present everywhere, except on nested structures of ```type Plugin struct {```

2021-03-12 14:23 UTC, gzigzigzeo commented on plugin/main.go
> +const (
Fixed style for private vars. Actually, I have a question regarding it. Private vars comments are not required nor by linter, nor by the CodeReviewComments. Do you consider it is a good practice?

2021-03-12 14:23 UTC, gzigzigzeo commented on plugin/message.go
> +// Message holds reflection information about message
Message represents reflection data on protoc messages.

2021-03-12 14:26 UTC, gzigzigzeo commented on test/main_test.go
> +func buildSubject(t *testing.T) (*Test, error) {
```schema.TestResourceDataRaw(t, SchemaTest(), fixutre)``` - it is required in this line

2021-03-12 14:26 UTC, gzigzigzeo commented on test/main_test.go
> +		panic(err)
Changed this completely to assert

2021-03-12 14:26 UTC, gzigzigzeo commented on test/main_test.go
> +	timestamp, _ := time.Parse(time.RFC3339, defaultTimestamp)
Fixed

2021-03-12 14:28 UTC, gzigzigzeo commented on plugin/field.go
> +	// GoTypeIsSlice Go type is a slice?
Done

2021-03-12 14:31 UTC, gzigzigzeo commented on plugin/field.go
> +		b.generator.Fail("unknown type for", b.descriptor.GetName(), b.fieldDescriptor.GetName())
I think, that is more severe than just bad parameter. This error is really fatal, but I'll change the style of this to the default (without Generator.Fail) everywhere.

2021-03-12 14:47 UTC, gzigzigzeo commented on main.go
> +	n1 := strings.Index(s, "package")
Now, replaced the whole fragment with much more readable regexp

2021-03-12 14:49 UTC, gzigzigzeo commented on plugin/field.go
> +func BuildField(g *generator.Generator, d *generator.Descriptor, f *descriptor.FieldDescriptorProto) *Field {
We skip fields in two cases: a) field exists in ExcludeFields b) field has oneOf type. I will change control flow here.

2021-03-12 16:40 UTC, klizhentas commented on config/main.go
> +// Package config contains global configuration variables and methods to parse them
the code that we generate should be Apache2 licensed too, so it's ok to add it there

2021-03-12 17:47 UTC, gzigzigzeo commented on plugin/field.go
> +func BuildField(g *generator.Generator, d *generator.Descriptor, f *descriptor.FieldDescriptorProto) *Field {
Anyway, I've converted to standard approach.

2021-03-12 17:57 UTC, gzigzigzeo commented on plugin/field.go
> +	f := b.field // shortrut
That's just syntax sugar. Removed them everywhere in favour of simple local variables.

2021-03-12 18:02 UTC, gzigzigzeo commented on plugin/field.go
> +// setMessage sets reference to nested message
I do not think that examples are appropriate in this case, but I definitely need to add general explanation of what's going on inside this file.

2021-03-13 01:26 UTC, r0mant commented on main.go
> +func replacePackageName(s string) string {
s -> fileContent

2021-03-13 01:26 UTC, r0mant commented on main.go
> +	packageReplacementRegexp = regexp.MustCompile("package (.*)\n")
Would `^package (.+)$` be more accurate? To make sure it only matches the full string and package name is not empty?

2021-03-13 01:26 UTC, r0mant commented on plugin/errors.go
> +Copyright 2015-2020 Gravitational, Inc.
2021

2021-03-13 01:26 UTC, r0mant commented on plugin/errors.go
> +// newInvalidFieldError creates unknown type error
creates new invalid field error

2021-03-13 01:26 UTC, r0mant commented on plugin/errors.go
> +// newInvalidMessageError creates unknown type error
creates new invalid message error

2021-03-13 01:26 UTC, r0mant commented on plugin/field.go
> +Copyright 2015-2020 Gravitational, Inc.
2021

2021-03-13 01:26 UTC, r0mant commented on plugin/main.go
> +const (
@gzigzigzeo Yeah, I would consider it a good practice, helps code readers enormously. I personally try to add useful godocs to private vars and methods where it may help the reader understand their purpose as well.

2021-03-13 01:26 UTC, r0mant commented on plugin/message.go
> +Copyright 2015-2020 Gravitational, Inc.
2021 (and on all other license headers)

2021-03-13 01:26 UTC, r0mant commented on plugin/message.go
> +// BuildMessage builds Message from its protobuf descriptor and
Unfinished sentence?

2021-03-13 01:26 UTC, r0mant commented on plugin/message.go
> +		return nil, err
trace.Wrap(err)

2021-03-13 01:26 UTC, r0mant commented on render/main.go
> +		return err
trace.Wrap here and below

2021-03-13 01:26 UTC, r0mant commented on test/test.proto
> +
Where did field number 12 go? :)

2021-03-15 08:29 UTC, gzigzigzeo commented on config/main.go
> +// Package config contains global configuration variables and methods to parse them
Added

2021-03-15 08:30 UTC, gzigzigzeo commented on README.md
> +    types.proto
I think, it would be better to show full call signature (the way of passing flags is important).

2021-03-15 08:32 UTC, gzigzigzeo commented on config/main.go
> +		Types[n] = struct{}{}
Types is passed from command-line. It is read-only value by nature. If it was accessed concurrently, that would happen after that values is created anyway, so, there would not be any problems anyway. IMHO lock would only complicate things here.

2021-03-15 08:56 UTC, gzigzigzeo commented on config/main.go
> +// ParseExcludeFields parses and sets ExcludeFields
I did some digging and understood why am I keeping to miss out this kind of errors. This check is disabled by default in `golangci-lint`. To keep things solid, I've used the linting configuration from here: https://github.com/gravitational/teleport/blob/master/Makefile#L294 
It has `--exclude-use-default` flag which explicitly disables this check (EXC0002) along with some others. I think, this setting should be turned off (`--exclude-use-default false`) and we need to explicitly specify `--exclude` flags for every check we do not need. Same for teleport-plugins. I also propose to create uniform .golangci.yml file for all repos. Should I create an issue? @klizhentas @r0mant

2021-03-15 09:06 UTC, gzigzigzeo commented on config/main.go
> +		ExcludeFields[n] = struct{}{}
It is read-only command-line argument, as well.

2021-03-15 09:52 UTC, gzigzigzeo commented on config/main.go
> +func SetDefaultPkgName(arg string) {
👍

2021-03-15 09:54 UTC, gzigzigzeo commented on config/main.go
> +	if arg == "" {
Makes sense, added here and everywhere.

2021-03-15 09:54 UTC, gzigzigzeo commented on config/main.go
> +	if arg == "" {
👍

2021-03-15 09:54 UTC, gzigzigzeo commented on config/main.go
> +	if arg == "" {
👍

2021-03-15 10:10 UTC, gzigzigzeo commented on config/main.go
> +func SetDuration(arg string) {
Naming makes sense, fixed. I think, you got it right. I could make sure that it contains valid type name, yes, but I can not check if a type exists itself at a proto file compile stage. Will think about it a bit.

2021-03-15 10:10 UTC, gzigzigzeo commented on main.go
> +Copyright 2015-2020 Gravitational, Inc.
👍

2021-03-15 10:14 UTC, gzigzigzeo commented on main.go
> +	p := plugin.NewPlugin()
Couldn't agree here. It goes against: https://github.com/golang/go/wiki/CodeReviewComments#variable-names This variables are very local, hence, they should use short names.

2021-03-15 10:17 UTC, gzigzigzeo commented on main.go
> +func fmt(resp *plugin_go.CodeGeneratorResponse) error {
This method formats code and removes unused imports as the nice side-effect 😄 Changed the comment and method name to `runGoImports`, which, in my opinion would be more accurate. WDYT?

2021-03-15 10:18 UTC, gzigzigzeo commented on main.go
> +		result, err := imports.Process("", []byte(*file.Content), &opts)
👍

2021-03-15 10:24 UTC, gzigzigzeo commented on main.go
> +func replacePackageName(s string) string {
Well, this variable is local. I think, the same rule is in effect here.

2021-03-15 10:26 UTC, gzigzigzeo commented on main.go
> +	packageReplacementRegexp = regexp.MustCompile("package (.*)\n")
Thanks, fixed.

2021-03-15 10:26 UTC, gzigzigzeo commented on plugin/errors.go
> +Copyright 2015-2020 Gravitational, Inc.
👍

2021-03-15 10:27 UTC, gzigzigzeo commented on plugin/errors.go
> +// newInvalidFieldError creates unknown type error
Done

2021-03-15 10:27 UTC, gzigzigzeo commented on plugin/errors.go
> +// newInvalidMessageError creates unknown type error
Done

2021-03-15 10:27 UTC, gzigzigzeo commented on plugin/field.go
> +Copyright 2015-2020 Gravitational, Inc.
👍

2021-03-15 10:27 UTC, gzigzigzeo commented on plugin/message.go
> +Copyright 2015-2020 Gravitational, Inc.
👍

2021-03-15 10:28 UTC, gzigzigzeo commented on plugin/message.go
> +// BuildMessage builds Message from its protobuf descriptor and
👍

2021-03-15 10:28 UTC, gzigzigzeo commented on plugin/message.go
> +		return nil, err
👍

2021-03-15 10:29 UTC, gzigzigzeo commented on render/main.go
> +		return err
👍

2021-03-15 10:32 UTC, gzigzigzeo commented on test/test.proto
> +
Fixed, thanks :-)

2021-03-18 15:47 UTC, r0mant approved these changes

2021-03-18 17:07 UTC, a-palchikov approved these changes

2021-03-18 17:12 UTC, gzigzigzeo commented on plugin/main.go
> +		p.Generator.Fail(err.Error())
gogo/protobuf plugin is supposed to fail this way, it's the convention. It calls os.Exit(-1).

2021-03-18 17:14 UTC, gzigzigzeo commented on test/custom_types.go
> +// BoolCustom custom bool array
BoolCustom is not an array. It represents an array element in this case.

2021-03-18 17:18 UTC, gzigzigzeo commented on test/main_test.go
> +Copyright 2015-2021 Gravitational, Inc.
I do not know how copyright years work in this case. If you think, it is safe to remove the lower boundary - I'll do it, but first I would consult with the legal team. @klizhentas WDYT?

2021-03-18 17:22 UTC, gzigzigzeo commented on plugin/field.go
> +	t, _ := b.generator.GoType(b.descriptor, b.fieldDescriptor)
b.generator.GoType will call generator.Fail and exit in case it can't return valid go type. So, I do not see this situation as really possible, but I'll add != "" check here just in case something goes wrong.

2021-03-19 15:20 UTC, klizhentas approved these changes

2021-03-19 15:22 UTC, merged